# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b12ecb828ec7b4485513256e2e826863ee002bcb5d5efef64ba7c4b31c5adf59d1f51befb489546bc204e96c5accc3c9837ad78693d8ca542c348624182563fc

test:
  secret_key_base: 47e75070c08d9dca322204265e0b65f2c580a97a53656bd92035ae1757253be9efbb651e33f965aebeaf2a42b99bd35ab60de3af7fac27c22fb8f09c6a19a0f7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
